// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv3w6LQk09VXE67XbLYs0Bsc0PmR5kxGE',
    appId: '1:463162705353:ios:65acda5ef690edc2a81418',
    messagingSenderId: '463162705353',
    projectId: 'se7ety-3ab29',
    storageBucket: 'se7ety-3ab29.firebasestorage.app',
    iosBundleId: 'com.eraasoft.fire',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD68G6aMv1woFS37KhR_wRn3bAxdTZqjE',
    appId: '1:463162705353:android:5311f6c1e857402aa81418',
    messagingSenderId: '463162705353',
    projectId: 'se7ety-3ab29',
    storageBucket: 'se7ety-3ab29.firebasestorage.app',
  );

}